# Generated by Django 4.1.2 on 2023-05-20 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sbentry',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('link', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='static/submitted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Scoreboard entries',
                'ordering': ['-submit_date'],
            },
        ),
    ]
